# API Configuration
base_url: "https://developer.apple.com"
docs_endpoint: "/tutorials/data/documentation/"

# Data Configuration
endpoint_file: "data/raw/endpoints.json"
processed_endpoint_file: "data/processed/processed_endpoints.json"